### ISSUE TITLE
Larger images for limited VRAM

### ISSUE THREAD

**Issue by marianobasti** [google-research/frame-interpolation#11]
Hey there! Great work and results on this research!

When inferencing, I've noticed that there is consideration for limitations with the available VRAM and the code adapts accordingly when allocating. But when I try the same with larger images the limited memory becomes an issue, and the inference yields no results. 
I was wondering what approach could solve this. Something I've done before with other repos is cropping the images in equal parts, processing them individually and then stitching them up, but maybe in this case that would be detrimental for the results. Any other ideas?

I'm running this on a NVidia RTX2070s 8gb

**Comment by fitsumreda** [comment]
Thanks! The Python codes currently do not do memory management. 

Your option of cropping and then stitching the model output sounds good to me. You might want to overlap the crops to minimize boundary effects.

**Comment by marianobasti** [comment]
I'll start writing an implementation this week then. Where in the pipeline
would it be best to implement this?

**Comment by fitsumreda** [comment]
You can create a new library file like this one (https://github.com/google-research/frame-interpolation/blob/main/eval/interpolator.py), and I'd be happy to review your PR.

**Comment by marianobasti** [comment]
I've forked the repo and created a small library called [eval/splitter.py](https://github.com/marianobasti/frame-interpolation/blob/main/eval/splitter.py). The splitter takes a numpy array of size (height,width,channels) and returns another of size (tile, height, width, channels) and the stitcher thakes that array and returns the original (height,width,channels). I'm thinking its functions can be called on [eval/interpolator.py](https://github.com/google-research/frame-interpolation/blob/main/eval/interpolator.py) at line 103.
I'm also seeing that the numpy array used when interpolating contains at dim=0 a dimension called 'batch_size' added on line 88 of [eval/util.py](https://github.com/google-research/frame-interpolation/blob/main/eval/util.py). What would that be for? I'm thinking it could be stripped and then added when splitting the frame.

**Comment by marianobasti** [comment]
Tried implementing on [eval/interpolator_test.py](https://github.com/marianobasti/frame-interpolation/blob/main/eval/interpolator_test.py) but I'm stuck at an error when testing, It looks like I'm parsing the wrong type of variables.


```
ValueError: Could not find matching function to call loaded from the SavedModel. Got:
  Positional arguments (3 total):
    * {'x0': <tf.Tensor 'inputs_1:0' shape=(1, 175, 175, 3) dtype=float64>, 'x1': <tf.Tensor 'inputs_2:0' shape=(1, 175, 175, 3) dtype=float64>, 'time': <tf.Tensor 'inputs:0' shape=(1, 1) dtype=float32>}
    * False
    * None
  Keyword arguments: {}

Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (3 total):
    * {'x0': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='x0'), 'time': TensorSpec(shape=(None, 1), dtype=tf.float32, name='time'), 'x1': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='x1')}
    * False
    * None
  Keyword arguments: {}

Option 2:
  Positional arguments (3 total):
    * {'x0': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs/x0'), 'time': TensorSpec(shape=(None, 1), dtype=tf.float32, name='inputs/time'), 'x1': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs/x1')}
    * False
    * None
  Keyword arguments: {}

Option 3:
  Positional arguments (3 total):
    * {'x0': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs/x0'), 'x1': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='inputs/x1'), 'time': TensorSpec(shape=(None, 1), dtype=tf.float32, name='inputs/time')}
    * True
    * None
  Keyword arguments: {}

Option 4:
  Positional arguments (3 total):
    * {'time': TensorSpec(shape=(None, 1), dtype=tf.float32, name='time'), 'x1': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='x1'), 'x0': TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='x0')}
    * True
    * None
  Keyword arguments: {}
```

**Comment by fitsumreda** [comment]
@marianobasti The codes support high resolution interpolation. Check here: https://github.com/google-research/frame-interpolation#change-log.

**Comment by marianobasti** [comment]
Thanks for the update!

I'm currently testing on a couple of 1920x1080 frames, and it's taken 50 minutes and still hasn't finished. In comparison, testing on a resolution of 400x400 took less than a minute in my system.

I'm guessing something's off.

**Comment by marianobasti** [comment]
I also noticed that the block size must be proportional to the actual width and height of the frame, so a parameter in the likes of `--patching_factor` could make it easier to use.

**Comment by fitsumreda** [comment]
Strange, what values did you set to block_height and block_width? I didn’t use a single patching factor, so it’d be possible to partition into a non- square shaped blocks. It currently does not have additional padding, so boundary effects may be present. If you have changes, feel free to creat a PR.

**Comment by marianobasti** [comment]
For the 1920x1080 frame I set block_width and block_height it to 480 and 270 respectively.

Tried the same with a 297x270 frame, setting block_width and block_height it to 99 and 90 respectively (a fourth of the size). Got the error

`tensorflow.python.framework.errors_impl.InvalidArgumentError: padded_shape[1]=293 is not divisible by block_shape[1]=2[Op:SpaceToBatchND]`

**Comment by fitsumreda** [comment]
That basically means, you subdivide the height by 99 or 90. That is not the desire behavior. 

Simply set --block_height and --block_width to 2 each. The codes will extract 4 patches (2*2) shaped (540,960) and stitch the interpolated patches. 

You are creating so many small patches, so it takes so long.

**Comment by marianobasti** [comment]
Ohh I see. My interpretation was that those parameters set the size of the block in pixels. My bad!

**Comment by marianobasti** [comment]
After multiple tests, I've found that the borders are notorious and adding paddings is a must. I've found that `tf.space_to_batch` has a parameter for padding, and it's explicitly set to 0 in your implementation. May I ask why is that?

**Comment by fitsumreda** [comment]
I implemented no-padding, and hasn't tested it on large images, it had some artifacts on the example photos in the repo, but they were not large enough to be noticeable. It's true tf.space_to_batch allows custom padding. Feel free to send me a PR with that change, if this is of interest to you.
