### ISSUE TITLE
Sharing FILM pretrained models on the Hugging Face Hub

### ISSUE THREAD

**Issue by osanseviero** [google-research/frame-interpolation#13]
Hi there!

Would you be interested in sharing your models in the [Hugging Face Hub](http://hf.co/models)? The Hub offers free hosting of over 30K models, and it would make your work more accessible and visible to the rest of the ML community. There is an existing [Google organization](https://huggingface.co/google) where these models could be shared.

Some of the benefits of sharing your models through the Hub would be:
* wider reach of your research to the ecosystem
* Open Source: versioning, commit history and diffs
* repos provide useful metadata about their tasks, languages, metrics, etc that make them discoverable
* multiple features from TensorBoard visualizations, PapersWithCode integration, and more

Creating the repos and adding new models should be a relatively straightforward process if you've used Git before. This is a [step-by-step guide](https://huggingface.co/docs/hub/adding-a-model) explaining the process in case you're interested. Please let us know if you would be interested and if you have any questions.

Happy to hear your thoughts,
**Omar and the Hugging Face team**

**Comment by fitsumreda** [comment]
Thanks for this! How different is this from the related on-going thread from Hugging face?
https://github.com/google-research/frame-interpolation/issues/9

**Comment by osanseviero** [comment]
Sorry! I missed that AK already reached out to you. Thanks, this is super cool work!
