### ISSUE TITLE
Creating TFrecord does not work for me. It runs the code and does exactly nothing.

### ISSUE THREAD

**Issue by altair199797** [google-research/frame-interpolation#15]

**Comment by fitsumreda** [comment]
Can you post your command and folder structure for the raw dataset? It is better to test the scripts with small datasets like the Middlebury-other.

**Comment by altair199797** [comment]
Thank you for your reaction!
It seems in the create_vimeo90k_tfrecord.py files it should be: def main(argv=None)  (the argv is missing)
otherwise the code is not executable.
and the beam pipeline is not working for me.
but doesn't matter I tried creating it without beam.
though tfrecord is unsuitable for me as I want to Train your FILM-network on X-Train (200 gb xD) to compare it.

**Important**:
Have you tried to train your network on X-Train? It seems to be the only high motion Training Dataset freely available.

Thank you in Advance!

**Comment by fitsumreda** [comment]
Thanks for pointing the X-Train data.

**Comment by fitsumreda** [comment]
Fixed by 86200bdfb1cd715d6e3fbb4a87b4babf24db4d07
