### ISSUE TITLE
dnn PoolForward launch failed when running interpolate_cli 

### ISSUE THREAD

**Issue by augustfr** [google-research/frame-interpolation#16]
I ran this command: `python3 -m frame_interpolation.eval.interpolator_cli --pattern "frame_interpolation/photos" --model_path ./pretrained_models/pretrained_models/film_net/Style/saved_model --times_to_interpolate 4 --output_video`

and this is the error:

`RuntimeError: tensorflow.python.framework.errors_impl.InternalError:  dnn PoolForward launch failed
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/average_pooling2d_1/PartitionedCall/AvgPool}}]] [Op:__inference_restored_function_body_13284]

Function call stack:
restored_function_body [while running 'Process directories']`

**Comment by fitsumreda** [comment]
Are you testing with the sample images "under photos"? Is your system set properly and is running on the GPU? See this relevant issues: https://github.com/nginyc/rafiki/issues/154

**Comment by augustfr** [comment]
Yes all the frames are in the photos folder. 

I use this same instance for running stylegan3 training and running lucid sonic dreams with no issues heavily utilizing the v100.

Not sure what's going on

**Comment by fitsumreda** [comment]
Setup your system according to the instruction in the README.
