### ISSUE TITLE
cannot create tfrecord of vimeo90k to recreate training

### ISSUE THREAD

**Issue by lilhuang** [google-research/frame-interpolation#17]
Hi, I am trying to create a tfrecord of vimeo90k in order to train the mode. I'm trying to run create_vimeo90K_tfrecord.py as explained in the docs, but keep getting the following error:

`I0228 11:58:52.708416 140056800593728 native_type_compatibility.py:248] Using Any for unsupported type: typing.Mapping[str, str]`
`I0228 11:58:52.709244 140056800593728 native_type_compatibility.py:248] Using Any for unsupported type: typing.Mapping[str, str]`
`I0228 11:58:52.710263 140056800593728 native_type_compatibility.py:248] Using Any for unsupported type: typing.Mapping[str, str]`

And no tfrecords are created. This seems to happen when the script calls `beam.io.tfrecordio.WriteToTFRecord`. My folder setup is:

`[root folder]`
`|--frame_interpolation`
`|   |--datasets`
`|   |   |--vimeo90k`
`|   |   |   |--tri_testlist.txt`
`|   |   |   |--tri_trainist.txt`
`|   |   |   |--vimeo_triplet.zip`
`|   |--create_vimeo90K_tfrecord.py`

and the command I run is:

`python3 -m frame_interpolation.datasets.create_vimeo90K_tfrecord --input_dir=frame_interpolation/datasets/vimeo90k/vimeo_triplet.zip --input_triplet_list_filepath=frame_interpolation/datasets/vimeo90k/tri_trainlist.txt --output_tfrecord_filepath=frame_interpolation/datasets/vimeo90k/vimeo90k_train`

Thanks for your help.

**Comment by fitsumreda** [comment]
The codes expect the unzipped folderpath. You might need to change this ‘ vimeo_triplet.zip’

**Comment by lilhuang** [comment]
Thanks for the tip; I've fixed it such that "triplet_dicts" in the aforementioned script gives the correct path for each individual image (meaning, the `input_dir=[root_dir]/sequences`), but I'm still getting the same error.

**Comment by fitsumreda** [comment]
I don’t see an error message from you first message. The highlighted texts indicate they are created ‘from absl.looging.info’. 

I’d suggest to first test the datasets scripts on small datasets like Middlebury-other.

**Comment by lilhuang** [comment]
I think they are created from [this](https://github.com/apache/beam/blob/14d02ee07f3da3f326e2d80ea38521ddf04c905c/sdks/python/apache_beam/typehints/native_type_compatibility.py#L248) script in the apache beam package, and then everything returns; I'm just unsure how to debug what the issue is, since no tfrecords are being created. I can try to test the scripts on Middlebury-other too, but eventually I'd like to try with vimeo, so I'd still want to figure out what's wrong.

**Comment by altair199797** [comment]
I know the bug, there are two bugs when you want to create a vimeo tfrecord.
1.  in create_vimeo90K_tfrecord.py, it needs to be def main(argv=None)
2. in util.py in line 190 where it states:  def process(self, triplet_dict: Mapping[str, str]) -> List[bytes]:
You simply have to delete the type specification "Mapping[str,str]" to resolve the bug you posted.

The beam pipeline is also not working for me. But you can simply do it without the beam pipeline.
I think if you replace the beam pipeline thing with this it should just work (I tested this code with another dataset):

`with tf.io.TFRecordWriter("X-Train.tfrecords") as writer:
    for i in triplet_dicts:
      tfexam = util.generate_image_triplet_example(i)
      writer.write(tfexam.SerializeToString())`

**Comment by fitsumreda** [comment]
Great, thank you for your suggestions and code snippets! Do you want to create a PR for it, can review and accept.

**Comment by altair199797** [comment]
You are welcome. No sry i haven't forked it etc. and I just changed the two things, but am no longer using the code.

**Comment by fitsumreda** [comment]
Fixed by 86200bdfb1cd715d6e3fbb4a87b4babf24db4d07
