### ISSUE TITLE
Too many command-line arguments

### ISSUE THREAD

**Issue by Xvcongqi** [google-research/frame-interpolation#19]
I use cmd of windows to run interpolator_test.py，but when I enter the parameter, it returns me”Too many command-line arguments.“
Below is my parameter settings ：
D:\Project\Interpolation between images\frame-interpolation-main\eval>python interpolator_test.py --frame1=D:\Project\Interpolation between images\frame-interpolation-main\photos\one.png --frame2=D:\Project\Interpolation between images\frame-interpolation-main\photos\two.png --model_path D:\Project\Interpolation between images\frame-interpolation-main\pretrained_models\film_net\Style\saved_model --output_frame D:\Project\Interpolation between images\frame-interpolation-main\photos
It returns :
A test script for mid frame interpolation from two input frames.

Usage example:
 python3 -m frame_interpolation.eval.interpolator_test \
   --frame1 <filepath of the first frame> \
   --frame2 <filepath of the second frame> \
   --model_path <The filepath of the TF2 saved model to use>

The output is saved to <the directory of the input frames>/output_frame.png. If
`--output_frame` filepath is provided, it will be used instead.

flags:

interpolator_test.py:
  --align: If >1, pad the input size so it is evenly divisible by this value.
    (an integer)
  --frame1: The filepath of the first input frame.
  --frame2: The filepath of the second input frame.
  --model_path: The path of the TF2 saved model to use.
  --output_frame: The output filepath of the interpolated mid-frame.

Too many command-line arguments.

please tell me what is the problem.Thank you!

**Comment by Xvcongqi** [comment]
@marianobasti 
thank you so much ！
I have another question:
I found out that the input image has limits on size and pixels.
I saw in another issue that you extended this project: eval/splitter.py. to overcome the above limitations. Did you succeed? If successful, how to do it?

**Comment by fitsumreda** [comment]
High res interpolation is now supported. Does it work for you? https://github.com/google-research/frame-interpolation#change-log

**Comment by GuusDeKroon** [comment]
I have the same command-line arguments error, am I missing something?

`python -m frame_interpolation.eval.interpolator_cli --pattern "D:\AI\anaconda\frame_interpolation\photos" --model_path D:\AI\anaconda\frame_interpolation\pretrained_models\film_net\Style\saved_model --times_to_interpolate 6 --output_video D:\AI\anaconda\frame_interpolation\_output\video.mp4`
