### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by ffdown** [google-research/frame-interpolation#26]
Use this code
`python -m frame_interpolation.eval.interpolator_cli --pattern "frame_interpolation\photos" --model_path <pretrained_models>\film_net\Style\saved_model --times_to_interpolate 6 --output_video`

Result without error: access denied.

**Comment by fitsumreda** [comment]
I assume you’re trying it out on Windows. The command looks right to me. Is there any file i/o permission issue?

**Comment by fitsumreda** [comment]
I was able to replicate your error, `<pretrained_models>` should point to the folder where pre-trained models are downloaded from google-drive. Try this:
```
python -m frame_interpolation.eval.interpolator_cli --pattern "frame_interpolation/photos" --model_path pretrained_models\film_net\Style\saved_model --times_to_interpolate 6 --output_video
```
