### ISSUE TITLE
Doesn't work enither in google colab nor conda

### ISSUE THREAD

**Issue by tralala87** [google-research/frame-interpolation#29]
When I run it in google colab, I upload my images in frames file, but nothing happens, despite code being finished.

When running in conda, I get:
At line:2 char:8
+      --pattern "frame_interpolation/photos" \
+        ~
Missing expression after unary operator '--'.
At line:2 char:8
+      --pattern "frame_interpolation/photos" \
+        ~~~~~~~
Unexpected token 'pattern' in expression or statement.
At line:3 char:8
+      --model_path <pretrained_models>/film_net/Style/saved_model \
+        ~
Missing expression after unary operator '--'.
At line:3 char:8
+      --model_path <pretrained_models>/film_net/Style/saved_model \
+        ~~~~~~~~~~
Unexpected token 'model_path' in expression or statement.
At line:3 char:19
+      --model_path <pretrained_models>/film_net/Style/saved_model \
+                   ~
The '<' operator is reserved for future use.
At line:4 char:8
+      --times_to_interpolate 6 \
+        ~
Missing expression after unary operator '--'.
At line:4 char:8
+      --times_to_interpolate 6 \
+        ~~~~~~~~~~~~~~~~~~~~
Unexpected token 'times_to_interpolate' in expression or statement.
At line:5 char:8
+      --output_video
+        ~
Missing expression after unary operator '--'.
At line:5 char:8
+      --output_video
+        ~~~~~~~~~~~~
Unexpected token 'output_video' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

What am I doing wrong?

**Comment by fitsumreda** [comment]
Are you using this colab? https://colab.sandbox.google.com/github/pytti-tools/frame-interpolation/blob/main/PyTTI_Tools_FiLM-colab.ipynb#scrollTo=-7TD7YZJbsy_

**Comment by tralala87** [comment]
Yes and also in another one mentioned in https://www.reddit.com/r/MediaSynthesis/comments/srxjfc/film_frame_interpolation_for_large_scene_motion/

**Comment by tralala87** [comment]
I tried again to run it in google colab, but can't find the "interpolated_frames" subdirectory where results should be saved.

**Comment by tralala87** [comment]
> Are you using this colab? https://colab.sandbox.google.com/github/pytti-tools/frame-interpolation/blob/main/PyTTI_Tools_FiLM-colab.ipynb#scrollTo=-7TD7YZJbsy_
I tried again to run it in google colab, but can't find the "interpolated_frames" subdirectory where results should be saved.

**Comment by fitsumreda** [comment]
![image](https://user-images.githubusercontent.com/15355345/167490209-75278365-df25-4512-81d3-935a54a7f67c.png)

"frame_dir" is something you specify, like your '/content/output/folder'. Once the interpolator runs, it should output into "/content/output/folder/interpolated_frames.

**Comment by fitsumreda** [comment]
Re-open if it's still not working for you.

**Comment by tralala87** [comment]
Sorry, but you didn't address the issue at all. Results should be saved in a subdirectory of frames_dir named "interpolated_frames" (as stated in the google colab 3. step). But there is no "interpolated_frames" to be found in my frames_dir.

**Comment by fitsumreda** [comment]
You can try this colab as an alternative, if the OOM is not related to FILM, https://colab.sandbox.google.com/drive/1sK0uc-GJxmdnaxHhYqD2afRknakpdTNZ. All credit to the colab goes to the colab authors.
