### ISSUE TITLE
"recursive_interpolation_passes"parameter didn't work

### ISSUE THREAD

**Issue by Poison413** [google-research/frame-interpolation#31]
When i run “PyTTI-Tools: FiLM.ipynb” this notebook, it seems that everytime I changed "recursive_interpolation_passes", the number of final frames was always 2048 and the length of output video was also the same. I don't know why.

**Comment by fitsumreda** [comment]
You should reach out to the colab authors for any questions on how to run the colabs

**Comment by fitsumreda** [comment]
[Colab: FILM PyTTI-Tools](https://colab.sandbox.google.com/github/pytti-tools/frame-interpolation/blob/main/PyTTI_Tools_FiLM-colab.ipynb#scrollTo=-7TD7YZJbsy_) works fine. Try closely following the instructions, if you still run into issues, feel free to re-open.
