### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by tralala87** [google-research/frame-interpolation#32]
When running:
python -m frame_interpolation.eval.interpolator_cli ^
     --pattern "frame_interpolation\photos" ^
     --model_path <pretrained_models>\film_net\Style\saved_model ^
     --times_to_interpolate 6 ^
     --output_video

I get:
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

**Comment by fitsumreda** [comment]
Remove the `^` new line character, and simply resolve the `<pretrained_modes>` to the folder that contains the pre-trained saved models (to be downloaded from google-drive). Try this:
```
python -m frame_interpolation.eval.interpolator_cli --pattern "frame_interpolation/photos" --model_path pretrained_models\film_net\Style\saved_model --times_to_interpolate 6 --output_video
```

**Comment by tralala87** [comment]
I already did that, but still get the error

**Comment by QiFuChina** [comment]
> I already did that, but still get the error

I also get this error, could you tell me how to fix this?

**Comment by tralala87** [comment]
I've deleted "frame_interpolation" from the code. That worked for me.
