### ISSUE TITLE
OOM error; how to reduce batch_size

### ISSUE THREAD

**Issue by tralala87** [google-research/frame-interpolation#34]
Hi.

I get OOM error while running on my laptop gpu. How to reduce batch_size?

**Comment by fitsumreda** [comment]
You might try to add the flags '--block_height 2 --block_wdith 2'.
It'll partition the image into 4 patches, and stitch them back after interpolation.

**Comment by tralala87** [comment]
It doesn't work when trying to interpolate multiple frames between two pictures.
When running: python -m eval.interpolator_cli --pattern "photos" --block_height 2 --block_width 2 --model_path pretrained_models\film_net\Style\saved_model --times_to_interpolate 6 --output_video
I get:
AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'

**Comment by fitsumreda** [comment]
Unfortunately, the `--block_height 2 --block_wdith 2` are currently implemented only for the `python -m eval.interpolator_test`, where it only interpolates a single middle frame. You can try that, if it works, it should be possible to apply the `--block_height 2 --block_width 2` flags to the `interpolator_cli` too.

**Comment by tralala87** [comment]
It works for single middle frame.

**Comment by fitsumreda** [comment]
see 97168492380331fd33d24e61ca1bdd986ccc1bd4
