### ISSUE TITLE
The interpolation animation effect was quite different between Pytt Tools Colab version and the web demo version

### ISSUE THREAD

**Issue by Poison413** [google-research/frame-interpolation#43]
I used same input images, but it seems the transition effect of web demo version is better than the one of pytt tools version. If you see the pictures, the detail of web demo one is more clear, not like the fuzzy effect of the pytt one. 
Do you have any ideas or explanations for that? When using the PYTT tools golab version, how can i get the same effect as the web demo one in Replicate?

web demo version
<img width="262" alt="Screen Shot 2022-06-24 at 5 49 39 PM" src="https://user-images.githubusercontent.com/41897862/175511221-0df7a65d-74ad-4197-9bfd-c4d0f4db75ef.png">

pytt tools version
<img width="351" alt="Screen Shot 2022-06-24 at 5 49 25 PM" src="https://user-images.githubusercontent.com/41897862/175511406-a60a120d-28f8-4f0b-974a-c3b848b41403.png">

**Comment by fitsumreda** [comment]
The [PyTTI Colab](https://colab.sandbox.google.com/github/pytti-tools/frame-interpolation/blob/main/PyTTI_Tools_FiLM-colab.ipynb#scrollTo=-7TD7YZJbsy_) linked in the README looks correct to me. 

I can only suspect the saved_model isn't pointing to the corrected version of the saved_model. You'd want to use the 'Style version' which can found at the [original location](https://drive.google.com/corp/drive/folders/1i9Go1YI2qiFWeT5QtywNFmYAA74bhXWj).

This is where the PyTTI colab is pointing at:
#url = "https://drive.google.com/drive/folders/1GhVNBPq20X7eaMsesydQ774CgGcDGkc6?usp=sharing"
share_id = "1GhVNBPq20X7eaMsesydQ774CgGcDGkc6"

**Comment by Poison413** [comment]
Thanks!!! Finally find the reason.
