### ISSUE TITLE
PyTTI-Tools and FILM colab don't work

### ISSUE THREAD

**Issue by tralala87** [google-research/frame-interpolation#47]
PyTTI-Tools and FILM colab don't work. Many issues also mentioned on reddit.

**Comment by fitsumreda** [comment]
The colab works fine. Follow the steps and provide the full path of where your input images live. 

E.g., to interpolate the "frame-interpolation/photos" in the FILM repo, I entered the full path into the frame_dir box, as: "/content/drive/MyDrive/interpolation/frame-interpolation/photos".

Several people seem to report problems, so I'm sharing a snapshot of my attempt at using the PyTTI-Tools Colab, it simply shows where the input images come from, and where the outputs will be saved. 

![image](https://user-images.githubusercontent.com/15355345/178861795-70b0069a-e1d3-490d-bc94-9a0aa2ba8985.png)

**Comment by tralala87** [comment]
Thank you for answer.
If using Windows 11, why do I have to delete the "frame_interpolation." part from "python3 -m frame_interpolation.eval.interpolator_test" ?
When running "python3 -m frame_interpolation.eval.interpolator_test" I get error, that module is not found.
But when I run "python3 -m feval.interpolator_test", it works?

**Comment by fitsumreda** [comment]
Glad it worked out for you!

If your current-working-directory is inside ‘frame_interpolation’, you have to delete the folder name when running the python3 commands.
