### ISSUE TITLE
about Recursive interpolation

### ISSUE THREAD

**Issue by menghuaa** [google-research/frame-interpolation#50]
Hello, does the interpolation algorithm you provided only train to generate one interpolated frame between two frames **during training**? I would like an algorithm that specifically generates multiple frames between two frames. Since I've never studied frame interpolation, I'd like to ask ：do all current frame interpolation algorithms train to generate one frame between two frames **during training** and generate multiple frames between two frames **by recursive interpolation** **during testing**? And is the number of frames generated by recursive interpolation limited, e.g. it must be the (2 to the power n)  - 1?

**Comment by fitsumreda** [comment]
I'll close this, since it's not related to the codes in this repo. Feel free to contact me via email (in the Readme).
