### ISSUE TITLE
Suggestion: Clarify filenames for interpolation

### ISSUE THREAD

**Issue by ItaiLeibowitz** [google-research/frame-interpolation#51]
Suggestion: Add a clarification in the readme for how to name the files for the frames to be interpolated. For example, maybe:

...Takes in a set of directories identified by a glob (--pattern). Each directory is expected to contain at least two input frames, with each contiguous frame pair treated as an input to generate in-between frames. Filenames for the frames should be named: "frame<9 digit integer such as 000000123>.png"

**Comment by fitsumreda** [comment]
Thank you for the suggestions. However, the frames do not need to be named as such, with 9 digit etc. The key requirement for the filename of the frames is that they should be naturally sortable with `natsort.natsorted(<list of frame filenames>)`. See the images in the `frame_interpolation/photos`, they are named one.png and two.png. If you apply natsort, their desired order is still preserved. That is the key!

**Comment by fitsumreda** [comment]
Fix added : 14fbba15c361f820ff569084e85c40ddd2b1c9b2
