### ISSUE TITLE
InvalidArgumentError: Input is empty - Alternative notebook error 

### ISSUE THREAD

**Issue by krango** [google-research/frame-interpolation#52]
I used to use this notebook all the time but now I am receiving this error when running the interpolate frames cell.
Any idea on how to fix this ?

RuntimeError: tensorflow.python.framework.errors_impl.InvalidArgumentError: Input is empty. [Op:DecodeImage] [while running 'Process directories']

**Comment by fitsumreda** [comment]
which colab is this referring?

**Comment by krango** [comment]
This is the FILM interpolation colab notebook specifically the link next to :
"An alternative Colab for running FILM on arbitrarily more images, rather than two"

**Comment by krango** [comment]
I also just checked the PYTTI tools : FILM notebook and received an error in that one as well:

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
OSError: [Errno 107] Transport endpoint is not connected
2022-07-29 01:48:51.820 | INFO     | __main__:<module>:14 - Interpolation comlpete.

**Comment by fitsumreda** [comment]
I'd encourage you to directly contact the colab authors for more support. Seems like many people have been able to run them without errors.
