### ISSUE TITLE
About lite model

### ISSUE THREAD

**Issue by Gilgamesh666666** [google-research/frame-interpolation#54]
Hi,

Thank you for sharing the excellent work! I want to try film on my own dataset, but the full film is a little heavy for my device. I had tried to adapt it by reducing the number of layers and channels but I failed to get a good result, I find that you have done some experiments on the lite version and the performance seems to still be very good. so would you release the lite version?

**Comment by fitsumreda** [comment]
Unfortunately I won't have the time to release the lite model. However, the paper has enough details for you to edit the config files under training/config and be able to recreate the mid and light versions.
