### ISSUE TITLE
More robust documentation please

### ISSUE THREAD

**Issue by heartlocket** [google-research/frame-interpolation#57]
Some more explanation of basic functionality would be incredible. For example, how does the order of images in the input folder affect the batch interpolation? how can users ensure that frames are sequentially read by FILM?

**Comment by fitsumreda** [comment]
Hi, thanks for your interest in our works. You can simply name the frames like (1.png, 2. png ... ). The eval codes internally apply `natsrot.natsorted` to order the frames in natural order. You can verify your frame names by running `natsort.natsorted` and their order should not change.
