### ISSUE TITLE
Code from the readme doesn't run

### ISSUE THREAD

**Issue by Lumoria** [google-research/frame-interpolation#58]
I don't know if there are some setup steps that aren't mentioned in the readme or if I messed something up but I get the error: 
`Error while finding module specification for 'frame_interpolation.eval.interpolator_test' (ModuleNotFoundError: No module named 'frame_interpolation')`

**Comment by fischp** [comment]
You're just running it from the wrong folder. frame_interpolation is the name of a folder. You need to run this command from outside the frame_interpolation folder.

so if it is C:\frame_interpolation\blahblahblah
You need to be at C:\ for this command to work.

**Comment by Lumoria** [comment]
> You're just running it from the wrong folder. frame_interpolation is the name of a folder. You need to run this command from outside the frame_interpolation folder.
> 
> so if it is C:\frame_interpolation\blahblahblah You need to be at C:\ for this command to work.

I'm running the code from just outside the "frame-interpolation" folder. The problem seems to be that python isn't installing this module for some reason. I'm running in a conda environment btw.

**Comment by fischp** [comment]
You don't understand. frame_interpolation isn't a module at all. It is the folder name. That is the name of the folder for the command.

If you were running it from inside the folder the command would instead be: 

python -m eval.interpolator_test --frame1 photos/one.png --frame2 photos/two.png --model_path pretrained_models/film_net/Style/saved_model --output_frame photos/middle.png

See in this command, eval is a folder as well.

**Comment by Lumoria** [comment]
> You don't understand. frame_interpolation isn't a module at all. It is the folder name. That is the name of the folder for the command.
> 
> If you were running it from inside the folder the command would instead be:
> 
> python -m eval.interpolator_test --frame1 photos/one.png --frame2 photos/two.png --model_path pretrained_models/film_net/Style/saved_model --output_frame photos/middle.png
> 
> See in this command, eval is a folder as well.

Understood, problem fixed! I hadn't renamed the folder from frame-interpolation to frame_interpolation from when it was cloned. Thank you very much!

**Comment by somenewaccountthen** [comment]
Also fell or this. @Lumoria 
GPU is blowing. Always a good sign.
 
Maybe massive update to main page and add a * in the example for idiots like me?  (we are many!)
