### ISSUE TITLE
upper limit # of of frames

### ISSUE THREAD

**Issue by prettydeep** [google-research/frame-interpolation#59]
Is there an upper limit to the number of frames that can be interpolated? I am trying to 1x interpolate ~4000 frames (640x480) and the process kills itself after some time without generating any interpolated frames.

**Comment by fitsumreda** [comment]
Hi, you may be running into OOM. You can try to pipe the images, see example snippets:
https://github.com/NVIDIA/unsupervised-video-interpolation/blob/master/eval.py#L151
https://github.com/NVIDIA/unsupervised-video-interpolation/blob/master/eval.py#L221-L223
