### ISSUE TITLE
How may i run the interpolator_cli.py on GPU?

### ISSUE THREAD

**Issue by ZJ-CAI** [google-research/frame-interpolation#6]
I input the command : python interpolator_cli.py --pattern "../photos" --model_path ../pretrained_models/film_net/Style/saved_model --times_to_interpolate 5

The program could successfully run but it runs on cpu instead of gpu. I wonder what should i do to make it run on my gpu device.

Thank you.

**Comment by fitsumreda** [comment]
I tested it again on a GPU, and it works successfully. Can you post the stdout logs? Do you see texts like 'Loaded cuDNN version xxxx' or 'Created device .../device:GPU:0' in the ouput?

**Comment by waminos** [comment]
I had the same problem as @ZJ-CAI . I am testing on a colab notebook.  I remove from the requirements the following 
and it worked fine for me. Hope it helps. 
**Delete from the requirements -->**
```
# Docker base image: `gcr.io/deeplearning-platform-release/tf2-gpu.2-6:latest`
tensorflow==2.6.2 # The latest should include tensorflow-gpu
tensorflow-datasets==4.4.0
tensorflow-addons==0.15.0
```

**Comment by fitsumreda** [comment]
Large image sizes can be handled with tiling, see Issue
https://github.com/google-research/frame-interpolation/issues/11
