### ISSUE TITLE
Are the training images' pixel values scaled to [0..1] ?

### ISSUE THREAD

**Issue by dmilkie** [google-research/frame-interpolation#62]
Are the training images' pixel values scaled to [0..1]?  Or are they left as uint8s?  or floats?

But [during eval](https://github.com/google-research/frame-interpolation/blob/14fbba15c361f820ff569084e85c40ddd2b1c9b2/eval/util.py#L29), I think that they _do_ get scaled to [0..1]:

```
def read_image(filename: str) -> np.ndarray:
  """Reads an sRgb 8-bit image.
  Args:
    filename: The input filename to read.
  Returns:
    A float32 3-channel (RGB) ndarray with colors in the [0..1] range.
```

**Comment by fitsumreda** [comment]
Hi, thanks for your interest in our works. 
Yes, in training we read images in the range of [0..1] floats too.

**Comment by dmilkie** [comment]
I am struggling to find where that occurs.  Would you mind pointing me to where in the code that conversion to [0..1] happens for the _training_ data?

**Comment by fitsumreda** [comment]
The're already encoded [0..1] into the TFRecord files that the codes read
from. Look at training/data_lib.py.

**Comment by dmilkie** [comment]
Aha.  Mystery solved.

I believe the raw .png string still gets serialized into the TFRecord file on disk.  The sneaky thing (at least I'm not used to) is that TF does a _conversion_ when retrieving the data from disk: 

`tf.io.decode_image(png_string)` gives you the original uint8 RGB [0..255], but
`tf.io.decode_image(png_string, dtype=tf.float32) `converts it to a [0..1] range.  

That isn't straight type casting, and isn't mentioned in the `tf.io.decode_image` [documentation](https://www.tensorflow.org/api_docs/python/tf/io/decode_image).  


```
In [16]: np.max(tf.io.decode_image(tf.io.read_file(img_path))) # RGB [0..255]
Out[16]: 93

In [17]: np.max(tf.io.decode_image(tf.io.read_file(img_path), dtype=tf.float32))   # Float [0..1]
Out[17]: 0.3647059

In [18]: np.max(tf.cast(tf.io.decode_image(tf.io.read_file(img_path)), dtype=tf.float32))  # Float [0..255]
Out[18]: 93.0
```

**Comment by fitsumreda** [comment]
Perhaps adding a comment about the pixel value range in the dataloader is helpful. I’m surprised the behavior of tf.io.decode_image isn’t documented fully.
