### ISSUE TITLE
Permission Issue When Trying To Train

### ISSUE THREAD

**Issue by jigglejiggle** [google-research/frame-interpolation#64]
Hello,
 When attempting to train using

`python -m frame_interpolation.training.train --gin_config frame_interpolation/training/config/film_net-L1.gin --base_folder frame_interpolation/trainingtest --label run1`

I receive the following error:
tensorflow.python.framework.errors_impl.PermissionDeniedError: Error executing an HTTP request: HTTP response code 403 with body '<?xml version='1.0' encoding='UTF-8'?><Error><Code>SecurityPolicyViolated</Code><Message>Request violates VPC Service Controls.</Message><Details>Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier: aLtoSx_oFl9dWx4WZCyDyUQ43UmTHYSvKLHLUf-2yKXOQMQ-cRAzkg</Details></Error>'
         when reading gs://xcloud-shared/fitsumreda/frame_interpolation/datasets/vimeo_interp_train.tfrecord-00003-of-00200
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]] [Op:IteratorGetNext]

My guess is that it is related to a permission setting, but I am unsure and do not know a solution how to fix from my side.
https://cloud.google.com/vpc-service-controls/docs/troubleshooting

**Comment by fitsumreda** [comment]
Hey, thanks for your interest in our work.

Are you running it from a local machine or on a VM sitting in a cloud or
farm?

I’d try to append ‘—cpu’ and test the training loop on a local machine. It
might help clarifying the error messages.

**Comment by jigglejiggle** [comment]
Thank you for the reply.
I'm running on a local machine with normal interpolation working.  
Ultimately, I'm trying to use the aux flag for additional outputs. It appears to only be accessible during training (which is why I'm trying to train), but maybe there is a different way to enable it ?

Per your recommendation, I tried adding the CPU flag:
python -m frame_interpolation.training.train --gin_config frame_interpolation/training/config/film_net-L1.gin --base_folder frame_interpolation/mytraining --label run1 --mode cpu

But still received the same error unfortunately.  It appears to be regarding the downloading of the vimeo dataset and not having permission ?

File "C:\ProgramData\Anaconda3\envs\frame_interpolation\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2727, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\ProgramData\Anaconda3\envs\frame_interpolation\lib\site-packages\tensorflow\python\framework\ops.py", line 6941, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.**PermissionDeniedError**: Error executing an HTTP request: HTTP response code 403 with body '<?xml version='1.0' encoding='UTF-8'?><Error><Code>**SecurityPolicyViolated**</Code><Message>Request violates VPC Service Controls.</Message><Details>**Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier: 9tZCPPdmrCG_8xKNNCAxLMW_J9nRZIuV1mG-qStudaQdOOXQ2ZtZuw**</Details></Error>'
         when reading gs://xcloud-shared/fitsumreda/frame_interpolation/datasets/vimeo_interp_train.tfrecord-00006-of-00200
         [[{{node MultiDeviceIteratorGetNextFromShard}}]]
         [[RemoteCall]] [Op:IteratorGetNext]

**Comment by fitsumreda** [comment]
Your config file is still pointing to the training data that is not publicly accessible. You need to change `gs://xcloud-shared/fitsumreda/frame_interpolation/datasets/vimeo_interp_train.tfrecord-00006-of-00200` to your own copy of Vimeo-90k TFRecords. There are instructions how to construct the dataset by yourself.

I'll close this issue, feel free to create an issue if you run into anything

**Comment by jigglejiggle** [comment]
Thank you for your help. I got it training now.  It threw this warning, but I will assume that that's normal.

UserWarning: Input dict contained keys ['y', 'path'] which did not match any model input. They will be ignored by the model.

**Comment by fitsumreda** [comment]
The warning is normal. It means the model graph doesn’t use the target
image ‘y’ and the image’s filepath string ‘path’. The target ‘y’ is usef in
the loss functions which isn’t part of the model graph.
