### ISSUE TITLE
interpolator_cli does not work with block_height/block_width

### ISSUE THREAD

**Issue by victor78** [google-research/frame-interpolation#69]
flags block_height/block_width work good with interpolator_test, but what about interpolator_cli?

I got such message:
**FATAL Flags parsing error: Unknown command line flag 'block_height'**

**Comment by marianobastiUNRN** [comment]
Patch processing is implemented in interpolator_test but not on interpolator_cli.
Might try adding the process done between lines 88-99 from interpolator_test, with `util.image_to_patches`, which returns an array of the image subdivided, `model_wrapper.interpolate(image_batch_1, image_batch_2, batch_dt)` does the interpolation (might want to use `util.interpolate_recursively_from_files` instead) and then `util.patches_to_image` the result to get the interpolated images.
The only problem I see is that `util.interpolate_recursively_from_files` would return a list of interpolated individual patches, so you'd need another function to iterate through all the patches lists and recover the corresponding frame patches to stitch them back toghether.

**Comment by victor78** [comment]
Thank you for your answer, @marianobastiUNRN !

I think for my purposes I'll create some batch script which will use interpolator_test with block_height/width inside. I think, I should to use various (maybe random) block width and height, when I interpolate a lot of frames to avoid a visual seam between blocks.

**Comment by marianobastiUNRN** [comment]
I've also wrote a batch file to run `interpolator_test`, it works pretty well.
Rn i'm trying to enable patching inside `interpolator_cli`

**Comment by fitsumreda** [comment]
Thanks @marianobastiUNRN. Feel free to also open a PR, I'd be happy to merge it, once it works fine.

**Comment by fitsumreda** [comment]
see 97168492380331fd33d24e61ca1bdd986ccc1bd4
