### ISSUE TITLE
How to run the Code on Windows + Anaconda ?

### ISSUE THREAD

**Issue by AlonDan** [google-research/frame-interpolation#7]
When trying to use the code example it won't work.
Probably it works on Linux, but Anaconda can't understand the current extra lines or something like that, I'm not sure how to make it work on Anaconda as I'm a newbie.

If anyone can explain step-by-step how to run the code in Anaconda on Windows it will be very helpful, until the official project will also show / explain how it's done on the main page.

Thanks ahead!

**Comment by opale17** [comment]
Same issue here tried my best to make it work with anaconda but the inference doesn't work for me

**Comment by fitsumreda** [comment]
Windows support has been added. See here: https://github.com/google-research/frame-interpolation#change-log
