### ISSUE TITLE
Poor results

### ISSUE THREAD

**Issue by tcapelle** [google-research/frame-interpolation#70]
Have been playing with the model on colab and I am unable to get good results:

https://user-images.githubusercontent.com/18441985/201387094-054b7252-7223-4729-9f0e-59d2c03c5366.mp4

I also tried with a simple rolling pringles on the ground:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/18441985/201388667-abef3e79-e62a-49fe-b6b3-26e666a030e5.png">

Any tips?
I am using the default checkpoint (film_net/Style)

**Comment by fitsumreda** [comment]
Which Colab are you using? I suspect (looking at the second example with three frames) that the model isn't running properly. If the motion magnitude is extreme, then you'd need to downsample the input images, or re-train/finetune on datasets with similar motion magnitude. We've ablations for this case in the paper that you can take a look at.

**Comment by tcapelle** [comment]
Thanks for the quick reply! I will try again on Monday. As we discussed on ECCV I am going to train this for extrapolation. It appears that the only change I need to make is in [this part](https://github.com/google-research/frame-interpolation/blob/313fb69e2af599b6f01891f0c3968f7af2da3f1f/models/film_net/interpolator.py#L163) and build the triplets accordingly.

**Comment by tcapelle** [comment]
I took 2 consecutive pictures and the interpolation works flawlessly, my bad! I am using the colab linked in the Readme (PyTTI-Tools: FiLM.ipynb) and running locally on my mac.

https://user-images.githubusercontent.com/18441985/201473479-e105f08e-94f6-4f18-b4a3-a08a9d851b07.mp4

**Comment by fitsumreda** [comment]
Sounds good! I'll close the issue.
