### ISSUE TITLE
Example commands are not tight

### ISSUE THREAD

**Issue by amirtha255** [google-research/frame-interpolation#72]
Minor issue:
Example commands refer to 'frame_interpolation' with an underscore but the GitHub repo is with a hyphen, namely 'frame-interpolation'

**Comment by genesst** [comment]
The repo is clone into the directory with the underscore, see README
![image](https://user-images.githubusercontent.com/13213650/203886146-fb5cfdf8-3714-4963-940f-fb8970c94042.png)

**Comment by fitsumreda** [comment]
See the installation instructions.
