### ISSUE TITLE
/content/input-frames_half/interpolated.mp4: No such file or directory

### ISSUE THREAD

**Issue by leokamal** [google-research/frame-interpolation#74]
/content/input-frames_half/interpolated.mp4: No such file or directory

**Comment by AIManifest** [comment]
Are you able to explain in detail? From the looks of it, the file doesn't exist, so you can't do anything with a file that doesn't exist. Are you trying to interpolate the file specified above? Or by the looks of it, it looks like you're trying interpolate half of the input frames, but you need to remove the `/interpolated.mp4` if that's your objective.
