### ISSUE TITLE
adding models/Spaces/datasets to Huggingface Hub

### ISSUE THREAD

**Issue by AK391** [google-research/frame-interpolation#9]
Hi, would you be interested in adding frame-interpolation to [Hugging Face Hub](https://huggingface.co/models)? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. There is already a [google AI](https://huggingface.co/google) organization on huggingface with models or we could setup a organization for the frame-interpolation team to add the models, spaces and datasets

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/akhaliq/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation. Thanks

**Comment by fitsumreda** [comment]
Hi, thanks and it'd be great to create a space for frame-interpolation! 
Using the existing Google AI organization sounds good, and help with the technical implementation is highly appreciated. 
Happy to review and accept if a PR is needed for this.

**Comment by AK391** [comment]
@fitsumreda greats i have added the models here https://huggingface.co/akhaliq/frame-interpolation will look into setting up a space

**Comment by osanseviero** [comment]
Hey @AK391! Thanks for setting it up! 

As we usually aim for 1 model per 1 repo, would it make sense to split things a bit? We would end up with 4 repos

- film_vgg
- film_l1
- film_style
- film-imagenet-vgg-verydeep-19

We have `from_pretrained_keras` in `huggingface_hub` that allows loading `SavedModel` and in theory, we could use it here. Finally, in the `Interpolator` constructor, we could allow loading the model from the Hub as well (A simple approach could be by loading from the hub when there is a `hf` prefix, that is, when `model_path="hf:/ak/film_vgg"`). WDYT? Is this something that makes sense?

**Comment by AK391** [comment]
@osanseviero thanks, set up the models as 4 separate repos and the space is up here https://huggingface.co/spaces/akhaliq/frame-interpolation
